In [ ]:
# Importacion de librerias para realizar EDA

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Se elimina libreria pytplot que no se utilizara en el proyecto 
# Se elimina la libreria numpy que no se utilizara en el proyecto

# Lectuda de dataset ventas de videjuegos y almacenamiento en variable df

df = pd.read_csv('/content/drive/MyDrive/EBAC/vgsales.csv')

1. Lectura del archivo, head, tail, sample, describe.  Validación de columnas numéricas para que funcione con todas.

In [2]:
# Se obtienen encabezados de dataset con funcion head

df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [3]:
# Se obtienen ultimas filas de dataset con funcion tail

df.tail()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

In [4]:
# Se obtienen filas aleatorias de dataset con funcion sample

df.sample(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
9175,9177,Godzilla: Save the Earth,XB,2004.0,Fighting,Atari,0.10,0.03,0.00,0.00,0.14
5156,5158,LEGO Batman 2: DC Super Heroes,PSV,2012.0,Action,Warner Bros. Interactive Entertainment,0.17,0.13,0.00,0.06,0.37
10132,10134,Yu Yu Hakusho: Tournament Tactics,GBA,2004.0,Strategy,Atari,0.08,0.03,0.00,0.00,0.11
10946,10948,Tak: The Great Juju Challenge,DS,2005.0,Platform,THQ,0.09,0.00,0.00,0.01,0.09
2030,2032,Shrek 2,GC,2004.0,Platform,Activision,0.73,0.26,0.01,0.03,1.02

In [5]:
# Se obtiene informacion del dataset con funcion describe

df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [6]:
# Validacion de columnas con funcion info

df.info()

# Se valida informacion correcta para valores numericos (Year y Sales)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

2. Elementos minimos

In [7]:
# --- 1. Total de videojuegos analizados ---

len(df['Name'].unique())

11493

In [8]:
# --- 2.Total de géneros analizados ---

len(df['Genre'].unique())

12

In [9]:
# --- 3. Total de Plataformas analizadas ---

len(df['Platform'].unique())

31

3. Ventas

In [10]:
# --- 1. Total de ventas por año ---

df.groupby('Year')['Global_Sales'].sum()

Year
1980.0     11.38
1981.0     35.77
1982.0     28.86
1983.0     16.79
1984.0     50.36
1985.0     53.94
1986.0     37.07
1987.0     21.74
1988.0     47.22
1989.0     73.45
1990.0     49.39
1991.0     32.23
1992.0     76.16
1993.0     45.98
1994.0     79.17
1995.0     88.11
1996.0    199.15
1997.0    200.98
1998.0    256.47
1999.0    251.27
2000.0    201.56
2001.0    331.47
2002.0    395.52
2003.0    357.85
2004.0    419.31
2005.0    459.94
2006.0    521.04
2007.0    611.13
2008.0    678.90
2009.0    667.30
2010.0    600.45
2011.0    515.99
2012.0    363.54
2013.0    368.11
2014.0    337.05
2015.0    264.44
2016.0     70.93
2017.0      0.05
2020.0      0.29
Name: Global_Sales, dtype: float64

In [11]:
# ---  2. Juegos mas vendidos por año ---

top1 = df.loc[df.groupby('Year')['Rank'].min()] # Agrupamos por año y biscamos el rank minimo de cada año para sacar el Top1 de cada año, usamos creat una dataset mostrando solo las filas de los top1 por año
top1[['Year', 'Name']].sort_values('Year', ascending = True) # Mostramos solo, el rank, año y nombre de cada top 1 por año.

         Year                                          Name
1      1985.0                             Super Mario Bros.
5      1989.0                                        Tetris
18     1990.0                             Super Mario World
422    1995.0                               Killer Instinct
4      1996.0                      Pokemon Red/Pokemon Blue
30     1998.0       Pokémon Yellow: Special Pikachu Edition
105    1998.0                                      Tekken 3
232    2002.0           The Legend of Zelda: The Wind Waker
25     2002.0                 Pokemon Ruby/Pokemon Sapphire
14393  2002.0                                      Dr. Muto
17     2004.0                 Grand Theft Auto: San Andreas
58     2004.0             Pokemon FireRed/Pokemon LeafGreen
252    2005.0                   Need for Speed: Most Wanted
19     2005.0  Brain Age: Train Your Brain in Minutes a Day
11     2005.0                                 Mario Kart DS
90     2005.0        Grand Theft Auto: Liberty City Stories
10     2005.0                                    Nintendogs
5959   2006.0                    Syphon Filter: Dark Mirror
6      2006.0                         New Super Mario Bros.
240    2006.0                                 Madden NFL 07
13     2007.0                                       Wii Fit
2      2008.0                                Mario Kart Wii
51     2008.0                           Grand Theft Auto IV
259    2008.0                                      Fable II
45     2009.0          Pokemon HeartGold/Pokemon SoulSilver
14     2009.0                                  Wii Fit Plus
3      2009.0                             Wii Sports Resort
133    2009.0                                  Halo 3: ODST
31     2010.0                       Call of Duty: Black Ops
53     2011.0                           Super Mario 3D Land
29     2011.0                Call of Duty: Modern Warfare 3
222    2011.0                           Batman: Arkham City
128    2012.0                          Assassin's Creed III
35     2012.0                    Call of Duty: Black Ops II
34     2012.0                    Call of Duty: Black Ops II
188    2013.0                                Tomodachi Life
16     2013.0                            Grand Theft Auto V
23     2013.0                            Grand Theft Auto V
72     2013.0                                     Minecraft

In [12]:
# --- 3. Plataformas con más ingresos por año. ---

df_plat = df.groupby(['Year', 'Platform'])['Global_Sales'].sum().reset_index()
rank_plat = df_plat.groupby('Year')['Global_Sales'].idxmax()

top_plat = df_plat.loc[rank_plat].sort_values('Year', ascending = True)
top_plat

       Year Platform  Global_Sales
0    1980.0     2600         11.38
1    1981.0     2600         35.77
2    1982.0     2600         28.86
4    1983.0      NES         10.96
6    1984.0      NES         50.09
9    1985.0      NES         53.44
12   1986.0      NES         36.41
14   1987.0      NES         19.76
17   1988.0      NES         45.01
20   1989.0       GB         64.98
25   1990.0     SNES         26.16
29   1991.0     SNES         16.21
35   1992.0     SNES         32.98
40   1993.0     SNES         40.01
50   1994.0     SNES         35.08
55   1995.0       PS         35.92
64   1996.0       PS         94.68
70   1997.0       PS        136.08
77   1998.0       PS        169.58
84   1999.0       PS        144.57
93   2000.0       PS         96.28
104  2001.0      PS2        166.43
113  2002.0      PS2        205.40
119  2003.0      PS2        184.29
125  2004.0      PS2        211.78
132  2005.0      PS2        160.65
143  2006.0      Wii        137.91
154  2007.0      Wii        154.97
163  2008.0      Wii        174.16
171  2009.0      Wii        210.44
179  2010.0     X360        171.05
184  2011.0      PS3        159.37
192  2012.0      PS3        109.49
201  2013.0      PS3        117.39
213  2014.0      PS4         98.76
223  2015.0      PS4        115.30
233  2016.0      PS4         39.25
238  2017.0      PS4          0.03
240  2020.0       DS          0.29

In [13]:
# --- Todos estos números desglosados por ingreso: NA, EU, JP, Otros y el Global, --
df.groupby('Year')[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum().T

Year,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,1989.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2020.0
NA_Sales,10.59,33.40,26.92,7.76,33.28,33.73,12.50,8.46,23.87,45.15,...,338.85,304.24,241.06,154.96,154.77,131.97,102.82,22.66,0.00,0.27
EU_Sales,0.67,1.96,1.65,0.80,2.10,4.74,2.84,1.41,6.59,8.44,...,191.59,176.73,167.44,118.78,125.80,125.65,97.71,26.76,0.00,0.00
JP_Sales,0.00,0.00,0.00,8.10,14.27,14.56,19.81,11.63,15.76,18.36,...,61.89,59.49,53.04,51.74,47.59,39.46,33.72,13.70,0.05,0.00
Other_Sales,0.12,0.32,0.31,0.14,0.70,0.92,1.93,0.20,0.99,1.50,...,74.77,59.90,54.39,37.82,39.82,40.02,30.01,7.75,0.00,0.02
Global_Sales,11.38,35.77,28.86,16.79,50.36,53.94,37.07,21.74,47.22,73.45,...,667.30,600.45,515.99,363.54,368.11,337.05,264.44,70.93,0.05,0.29

In [14]:
df.sample(4)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
8450,8452,Cubivore: Survival of the Fittest,GC,2002.0,Adventure,Nintendo,0.01,0.00,0.15,0.00,0.17
319,320,Mario & Luigi: Bowser's Inside Story,DS,2009.0,Role-Playing,Nintendo,2.26,0.48,0.81,0.27,3.83
7438,7440,Shrek: Reekin' Havoc,GBA,2003.0,Platform,TDK Mediactive,0.15,0.06,0.00,0.00,0.21
5398,5400,Backstreet Billiards,PS,1998.0,Misc,ASCII Entertainment,0.19,0.13,0.00,0.02,0.34

In [15]:
# --- 4. Gráfico de comparación de ventas entre géneros por año ---


df_generos = df.groupby(['Year','Genre'])['Global_Sales'].sum().reset_index()

fig = px.line(df_generos,
              x='Year',
              y='Global_Sales',
              color='Genre',
              title='Comparación de Ventas de Videojuegos por Género a lo largo de los Años',
              labels={'Global_Sales', 'Year', 'Genre'})
fig.show()

In [16]:
# --- 5. Insights: 2 Gráficos adicionales interesantes ---

# Comparawcion de ventas por region
df_region = df.groupby('Year')[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum().reset_index()
df_region = df_region.melt(id_vars = 'Year', value_vars = ['NA_Sales','EU_Sales','JP_Sales','Other_Sales'], var_name = 'Region', value_name = 'Sales')

fig = px.line(df_region, x = 'Year', y = 'Sales', color = 'Region')
fig.show()

In [17]:
# --- 5. Insights: 2 Gráficos adicionales interesantes ---
# Evolucion de ventas por plataforma por año

df_plat = df.groupby(['Year', 'Platform'])['Global_Sales'].sum().reset_index()


fig = px.line(df_plat, x = 'Year', y = 'Global_Sales', color = 'Platform')
fig.show()

**Revisar el EDA del ejercicio anterior y añadir siguientes elementos, basados en los últimos 4 años**

In [18]:
# --- 1. Qué género ha tenido el mayor y menor crecimiento ---

df_gen = df.groupby(['Year','Genre'])['Global_Sales'].sum().reset_index()
df_gen = df_gen[df_gen['Year'] > 2010] # Tomando como ultimo año 2015 ya que de ese año en adelante hay pperdida o falta de informacion

fig = px.line(df_gen, x = 'Year', y = 'Global_Sales', color = 'Genre')
fig.show()

In [21]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [36]:
 # --- 2. Qué plataforma ha tenido el mayor y menor crecimiento ---

df_plat = df.groupby(['Year', 'Platform'])['Global_Sales'].sum().reset_index()
df_plat = df_plat[df_plat['Year'] > 2010]
df_plat = df_plat[df_plat['Year'] < 2015]

 fig = px.line(df_plat, x = 'Year', y = 'Global_Sales', color = 'Platform')
 fig.show()

In [ ]:
# Concuciones ejercicio anterior:

# Hasta el año 2015 las plataformas con mayor crecimiento respecto a su mes anterior fueron: PS4 y XOne,
# En cambio las de menor crecimiento fueron: PS3 y X360

In [39]:
# --- 3. Qué videojuego ha tenido el mayor y menor crecimiento ---
df_vid = df.groupby(['Year', 'Name'])['Global_Sales'].sum().reset_index()
df_vid = df_vid[df_vid['Year'] > 2010]
df_vid = df_vid[df_vid['Year'] < 2015]

fig = px.line(df_vid, x = 'Year', y = 'Global_Sales', color = 'Name')
fig.show()

In [ ]:
# Concuciones ejercicio anterior:

# Hasta el año 2015 el videojuego con mayor crecimiento respecto a su mes anterior fue: Grand Theft Auto V,
# En cambio el de menor crecimiento fue: Minecraft